const CardsApi = [
    {
      id: 1,
      heading: "Major crops",
      data1: "Wheat",
      value1: "1500",
      data2: "Maize",
      value2: "1000",
      data3: "Potato",
      value3: "750",
      data4: "Orchards",
      value4: "350",
      data5: "Fooder",
      value5: "200",
    },
    {
        id: 2,
        heading: "Crop Water Demand",
        data1: "Main Canal",
        value1: "7500",
        data2: "Balloki",
        value2: "800",
        data3: "Okara",
        value3: "1500",
        data4: "Sahiwal",
        value4: "300",
        data5: "Khanewal",
        value5: "2200",
      },
      {
        id: 3,
        heading: "Soil Moisture Condition",
        data1: "LBDC Average",
        value1: "15.5 %",
        data2: "Balloki",
        value2: "21 %",
        data3: "Okara",
        value3: "12 %",
        data4: "Sahiwal",
        value4: "16 %",
        data5: "Khanewal",
        value5: "13 %",
      },
      {
        id: 4,
        heading: "Proposed Schedual",
        data1: "Main Canal",
        value1: "6500",
        data2: "Balloki",
        value2: "500",
        data3: "Okara",
        value3: "1400",
        data4: "Sahiwal",
        value4: "2600",
        data5: "Khanewal",
        value5: "2000",
      },
  ];
  
  export default CardsApi;